version: '3'
services:
  php:
    container_name: p-php
    build:
      context: .
      dockerfile: web.dockerfile
    restart: always
    volumes:
      - ../.:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - db
    links:
      - db

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8001:80
    depends_on:
      - db
    links:
      - db

  db:
    container_name: p-mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - ./db_files:/docker-entrypoint-initdb.d/
    ports:
      - 3309:3306
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=p_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=12345678
      - MYSQL_ROOT_HOST=%
